Add : 색상 사이즈 선택창 제품별 적용
wecode-bootcamp-korea/fullstack3-1st-wepleshop-frontend pull request #22
Opened 2022-01-07 11:20 UTC by GDandTOP

# PR 체크리스트

### PR을 올렸다면 아래 사항은 반드시 지켜주세요.

- [v] Linked Issues에서 적절한 이슈 하나를 걸어두었습니다.
- [v] Labels에서 적절한 라벨을 부착하였습니다.
- [v] 본 PR을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

### 아래 사항까지 모두 체크되어야만 리뷰 요청 라벨을 달 수 있고, code review를 받을 수 있습니다.

- [v] 기능이 제대로 실행되는지 확인 하였습니다.
- [v] npm start로 구현한 화면 혹은 기능을 확인할 수 있습니다.
- [ ] self-refactoring으로 wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.

### Peer Review

- [ ] 팀원 최소 2명 이상으로부터 Peer Review를 받고, 반영하였습니다.

> 마크다운에서 체크를 하기 위해서는 [x] 이렇게 수정하시면 됩니다. [x ], [ x ] 가 아니라 정확하게 [x]여야 합니다. 혹은 마우스 클릭으로 체크해주세요.

# 구현 Postman

(여기에 Postman 결과물을 첨부해주세요. 캡쳐를 하거나 혹은 요청/응답을 텍스트로 기록해주세요.)

# 이슈 체크리스트

(여기에 이슈에서 계획한 상세 구현 사항들을 체크리스트로 만들어 구현할 때마다 체크해주세요.)

- [ ] (예시) 회원가입 기능 레이어링
- [ ] (예시) 암호화 비밀번호 저장 구현

## 기타 질문 및 특이 사항

(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

- (예시) 이용약관 체크박스 기능 구현 로직이 너무 지저분하고 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다!

2022-01-07 12:12 UTC, quark4904 requested changes
LGTM!

2022-01-07 12:12 UTC, quark4904 commented on src/pages/Detail/Detail.js
>      fetch('http://localhost:8000/products/details', {
```suggestion
    fetch(POST_SIGNIN_API, {
```
이런식으로 변경을 하시는게 좋을 것 같습니다.
다른분들 코드 보시면 fetch에 위와 같이 변수로 들어가 있을거예요.
그리고 config.js를 보면 해당 변수가 export 되어 있구요~

2022-01-07 12:12 UTC, quark4904 commented on src/pages/Detail/ColorList.js
> +    <li>
사이즈는 li에 className이 있던데, color는 없어도 되려나요~? 그냥 궁금해서요ㅎ

2022-01-07 12:22 UTC, GDandTOP commented on src/pages/Detail/ColorList.js
> +    <li>
좋은 지적 감사합니다! 아마 이 부분은 상단 태그에서 css를 적용했을 겁니다! class를 따로 지정하지 않았네요..

2022-01-07 12:22 UTC, GDandTOP commented on src/pages/Detail/Detail.js
>      fetch('http://localhost:8000/products/details', {
알겠습니다!

2022-01-09 05:21 UTC, quark4904 approved these changes

2022-01-09 07:23 UTC, woongstaa approved these changes
LGTM

2022-01-09 07:23 UTC, pd0203 approved these changes
LGTM

2022-01-09 07:23 UTC, merged